require 'documents/doc_builder'
require 'documents/documents_helper'
require 'documents/document_builder'
require 'documents/empty_document_builder'

require 'documents/common/schedule_info'

require 'documents/generators/sheet_builders/work_with_simple_sheet'
require 'documents/generators/sheet_builders/work_with_sub_exercises'
require 'documents/generators/sheet_builders/work_without_sub_exercises'

require 'documents/generators/subscription_contract_builders/government_contract'
require 'documents/generators/subscription_contract_builders/another_contract'
require 'documents/generators/subscription_contract_builders/student_contract'
require 'documents/generators/order_contract_builders/another_contract'
require 'documents/generators/order_contract_builders/student_contract'

require 'documents/generators/subscription_contract'
require 'documents/generators/payer_agreement'
require 'documents/generators/practice_agreement'
require 'documents/generators/addition_order'
require 'documents/generators/expulsion_order'
require 'documents/generators/questionnaire'
require 'documents/generators/multiple_questionnaire'
require 'documents/generators/ladder_sheet'
require 'documents/generators/final_work_sheet'
require 'documents/generators/sheet'
require 'documents/generators/exam_sheet'
require 'documents/generators/practice_work_sheet'
require 'documents/generators/hairdresser_work_sheet'
require 'documents/generators/vacation_order'
require 'documents/generators/final_work_registry'
require 'documents/generators/attendance_log'
require 'documents/generators/group_list'
require 'documents/generators/change_group_order'
require 'documents/generators/expulsion_notification'
require 'documents/generators/payment_receipt'
require 'documents/generators/order_contract'
require 'documents/generators/addition_period_order'
require 'documents/generators/expulsion_period_order'
require 'documents/generators/working_off_sheet'
require 'documents/generators/education_certificate'