source 'http://rubygems.org'

gem 'rails', '4.2.1'
gem 'rake', '10.4.2'

source 'http://gems.coalla.ru' do
  gem 'coalla-cms', '0.4.4.3'
  gem 'coalla-deploy', '0.1.10'
end

gem 'pg', '0.18.1'
# gem 'mysql'
gem 'activerecord-fb-adapter'
gem 'russian'
gem 'acts_as_list', '0.6.0'
gem 'remotipart', '1.3.1'
gem 'rmagick'
gem 'will_paginate', '3.0.7'
gem 'active_attr', '0.8.5'
gem 'sitemap_generator', '5.1.0'
gem 'whenever', '0.9.4'
gem 'holder_rails', '2.6.0'
gem 'tzinfo-data'
gem 'sprockets', '2.12.3'
gem 'backbone-rails', '1.1.2'
gem 'enumerize', '0.11.0'
gem 'sequenced', '3.1.1'
gem 'browser', '2.5.1'

gem 'jquery-ui-rails', '5.0.5'
gem 'jquery-fileupload-rails', '0.4.5'

gem 'ckeditor', '4.1.0'

gem 'mysql2'
gem 'thinking-sphinx', '3.4.2'

gem 'truncate_html', '0.9.3'

gem 'cancancan', '1.10.1'
gem 'meta-tags', '2.4.1'
gem 'gon', '5.2.3'

gem 'annotate', '2.6.8'
gem 'uglifier', '2.7.1'
gem 'js-routes', '1.0.1'

gem 'impressionist', '1.5.1'
gem 'friendly_id', '5.1.0'

gem 'delayed_job_active_record', '4.1.1'
gem 'daemons', '1.2.2'

gem 'omniauth', '1.2.2'
gem 'omniauth-oauth2', '1.3.1'
gem 'omniauth-facebook', '4.0.0'
gem 'omniauth-vkontakte', '1.3.3'
gem 'omniauth-odnoklassniki', '0.0.4'
gem 'hashie', '3.4.6'
gem 'charlock_holmes', '0.7.6'
gem 'devise', '3.5.6'

gem 'symmetric-encryption', '3.7.2'

gem 'fotoramajs', '4.6.4'
gem 'pdf-reader', '1.3.3'

gem 'paranoia', '2.1.4'
gem 'ransack', '1.7.0'

gem 'cocoon', '1.2.8'
gem 'amoeba'
gem 'gibbon', '3.0.1'

gem 'amorail', '0.3.0'

gem 'jbuilder', '2.4.0'

gem 'odf-report', '0.5.1'
gem 'libreconv', '0.9.3'
gem 'numbers_and_words', '0.10.5'
gem 'petrovich', '1.1.1'

gem 'httparty', '0.15.7'

gem 'standalone_typograf', '3.0.2'

gem 'rubyXL', '3.1.0'
gem 'lograge', '0.7.1'
gem 'logstash-event', '1.2.02'

gem 'yandex-api'
gem 'direct-api-v5'
gem 'google-adwords-api'
gem 'google_drive', '~> 2.1', '>= 2.1.1'
gem 'axlsx', '2.1.0.pre'
gem 'zip-zip', '0.3'

gem 'bourbon', '4.2.7'
gem 'neat', '1.8.0'
gem 'transition-events-js', '0.2.1'

gem 'video_thumb', '0.1.2'
gem 'uni_sender', '0.0.5'

gem 'carrierwave', '0.11.2'
gem 'piet', '~> 0.2.5'

gem 'survey_monkey_api', '~> 0.2.4'

gem 'httplog', '~> 1.0.3'

gem 'rack-rewrite'
gem 'scenic', '1.4'
gem 'breadcrumbs_on_rails', '~> 3.0', '>= 3.0.1'
gem 'breadcrumbs_on_rails-json_ld'

gem 'formtastic', '~> 3.1', '>= 3.1.5'
gem 'inline_svg'

group :production, :staging do
  gem 'unicorn'
  gem 'unicorn-rails'
  gem 'unicorn-worker-killer'
  gem 'exception_notification'
end

group :development do
  gem 'awesome_print', require: 'ap'
  gem 'ruby-prof'
  gem 'thin'
  gem 'eventmachine'
  gem 'haml-rails'
  gem 'letter_opener'
  gem 'quiet_assets'
  gem 'byebug'
  gem 'web-console'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rails-controller-testing'
  gem 'rspec-rails'
  gem 'spring-commands-rspec'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'faker'
  gem 'guard-rspec'
  gem 'launchy'
  gem 'webmock'
end
