# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  paykeeper_secret: 5rC9eCn50K
  unisender:
    api_key: 516z3knytkodsnadkr5kk7r3zmagpydkkt9duody
    lists:
      cosmetic: 9475507
      barbershop: 14840001
  mindbox:
    secret_key: LJySh6wiSytav5d0NCVf
    api_endpoint: https://api.mindbox.ru/
    endpoint_id: Cosmeticruwebsite
    csv_api_key: YXBpd2ViOmxAZE9CUiZI
    csv_api_endpoint: https://cosmeticru-services.directcrm.ru/
  amocore_callbak_url:
    cosmetic: https://api.amocore.in/cosmeticru/integration/call_back/wmhju09engjvn2m2z2n3rxdvzxnizz09/
    barbershop: https://api.amocore.in/cosmeticru/integration/call_back_sikorsky/wmhju09engjvn2m2z2n3rxdvzxnizz09

tkb: &tkb
  tkb_api:
    url: https://paytest.online.tkbbank.ru/
    login: T1903100944ID
    merchant_id: 100944
    api_key: Z7VseefKNVbOCCQhbNP6VMw62j7U08RerZrNGSf03u8VKSFyrNcw5J3oLYz3gvTNe6xMkcKsHYcBMLwjNJDo5uhR5dcSskUJLvRNv3nocUYgFBLaBqrG1FQTYPPh808wdDZr2TXTvpkmFbkDBbrc3nQeO6YQofokVCdcMugSCGkMvEoXEmP7K6B0WVM44hFqa8Ad6i1h4JJxbeTjTbkczqLXampZSkXub4MvekZwtHcbxeYScCm25DZTyMcV2czT

development:
  <<: *common
  <<: *tkb
  courses_shop_domain: cosmeticru.lvh.me
  secret_key_base: ebf9f26e674bbf0a330658223171eba5b0996aec9518d8f4584280e1b4bb8957dfee73e0211d09ec10d6a4f3f5527fa932d7571ba5931b585bb4449834637583
  vkontakte_app_id: 5761664
  vkontakte_app_secret: EdltG8uCXTYf35NuCAt1
  facebook_app_id: 206764243105207
  facebook_app_secret: cdff83aee6ce0fc41916830b44e5ecaa
  odnoklassniki_app_id: 1249056512
  odnoklassniki_app_secret: B1EFB598CDA9B9754B591F5D
  odnoklassniki_public_key: CBAIBEHLEBABABABA
  paykeeper_url: "http://coalla.server.paykeeper.ru/order/inline?"
  paykeeper_form_url: "http://demo.paykeeper.ru/create/"
  mailchimp_api_key: 9ec164b3c56ca54e5bc56d1b168034c5-
  host: "http://lvh.me:3000"

  amorail:
    usermail: "dev@coalla.ru"
    api_key: "07e0f3e6736762da760a2497b05197c4"
    api_endpoint: "https://new56e12ee148901.amocrm.ru/"

  seopult:
    username: "Dimakuz"
    password: "rdshiv50027052013"
    api_endpoint: "api.seopult.ru"

  co_magick:
    login: seva@cosmeticru.com
    password: BbdcEXAo
    api_endpoint: "http://api.comagic.ru/api"

  lifepay:
    login: 79687820846
    api_key: ad518aff22e0cdb6775962a1bda0dd7b
    api_endpoint: "https://sapi.life-pay.ru/"

  smsc:
    base_url: "http://smsc.ru/sys"
    login: Cosmeticru
    password: SMSCrdshiv500

  shops_domains:
    cosmetic: cosmeticru.lvh.me
    barbershop: lvh.me

  voximplant:
    api_endpoint: https://api.voximplant.com/platform_api/
    account_id: 2348659
    api_key: ef7d082b-2b8c-42af-813d-6b62fc016301
    application_id: 4173747
    rule_id: 328350

staging:
  <<: *common
  <<: *tkb
  courses_shop_domain: cosmeticru.coalla.ru
  secret_key_base: 473c6ea05a9998e81aaa0336a166b54556ce723c595526b33e39a814847dc8a721452a07fa0b75dade9c13b2041ce17de96ac997c2d4c20e8bfda1998750348c
  vkontakte_app_id: 5763390
  vkontakte_app_secret: haPO6QjyjgGNdDeLgrPN
  facebook_app_id: 792478917576751
  facebook_app_secret: d6f1fd46dc808f1f746fe9566e5b1031
  odnoklassniki_app_id: 1249066752
  odnoklassniki_app_secret: 13FF608D108C48CA61116311
  odnoklassniki_public_key: CBAQDEHLEBABABABA
  paykeeper_url: "http://coalla.server.paykeeper.ru/order/inline?"
  paykeeper_form_url: "http://coalla.server.paykeeper.ru/create/"
  mailchimp_api_key: 9ec164b3c56ca54e5bc56d1b168034c5-us6
  host: "http://cosmetic.coalla.ru"

  amorail:
    usermail: "dev@coalla.ru"
    api_key: "07e0f3e6736762da760a2497b05197c4"
    api_endpoint: "https://new56e12ee148901.amocrm.ru/"

  seopult:
    username: "Dimakuz"
    password: "rdshiv50027052013"
    api_endpoint: "api.seopult.ru" 

  co_magick:
    login: seva@cosmeticru.com
    password: BbdcEXAo
    api_endpoint: "http://api.comagic.ru/api"

  lifepay:
    login: 79687820846
    api_key: ad518aff22e0cdb6775962a1bda0dd7b
    api_endpoint: "https://sapi.life-pay.ru/"

  smsc:
    base_url: "http://smsc.ru/sys"
    login: Cosmeticru
    password: SMSCrdshiv500

  shops_domains:
    cosmetic: cosmeticru.coalla.ru
    barbershop: cosmetic.coalla.ru

  voximplant:
    api_endpoint: https://api.voximplant.com/platform_api/
    account_id: 2348659
    api_key: f7926543-f845-42e0-859b-bdcdc2eae90a
    application_id: 4173747
    rule_id: 328350

production:
  <<: *common
  <<: *tkb
  courses_shop_domain: www.cosmeticru.com
  secret_key_base: b53cebd31fbcdcc216407d0f9085507e643e7846df34ac75f9f9847e83adbc227de5400d641b2617b395a1e967ab74df100f664d82ad605b799c64295482c9d9
  vkontakte_app_id: 5866091
  vkontakte_app_secret: Z3JA6lAQ2xnDk5hPWgMJ
  facebook_app_id: 1239651659487018
  facebook_app_secret: d24d26481cb2e3a7c2137d450b4b1394
  odnoklassniki_app_id: 1249745920
  odnoklassniki_app_secret: 0FDE8C30DFF6389819F41A3C
  odnoklassniki_public_key: CBANJOHLEBABABABA
  paykeeper_url: "http://cosmeticru.server.paykeeper.ru/order/inline?"
  paykeeper_form_url: "https://cosmeticru.server.paykeeper.ru/create/"
  mailchimp_api_key: 9ec164b3c56ca54e5bc56d1b168034c5-us6
  host: "https://www.sikorsky.academy"

  amorail:
    usermail: "vl@coalla.ru"
    api_key: "42663fdbc58b3bd28d649fcefc8998124b209975"
    api_endpoint: "https://cosmeticru.amocrm.ru/"

  seopult:
    username: "Dimakuz"
    password: "rdshiv50027052013"
    api_endpoint: "api.seopult.ru"

  co_magick:
    login: seva@cosmeticru.com
    password: BbdcEXAo
    api_endpoint: "http://api.comagic.ru/api"

  lifepay:
    login: 79687820846
    api_key: ad518aff22e0cdb6775962a1bda0dd7b
    api_endpoint: "https://sapi.life-pay.ru/"

  smsc:
    base_url: "http://smsc.ru/sys"
    login: Cosmeticru
    password: SMSCrdshiv500

  shops_domains:
    cosmetic: cosmeticru.com
    barbershop: sikorsky.academy

  voximplant:
    api_endpoint: https://api.voximplant.com/platform_api/
    account_id: 2359642
    api_key: f7926543-f845-42e0-859b-bdcdc2eae90a
    application_id: 4178437
    rule_id: 331877

test:
  <<: *common

  secret_key_base: ebf9f26e674bbf0a330658223171eba5b0996aec9518d8f4584280e1b4bb8957dfee73e0211d09ec10d6a4f3f5527fa932d7571ba5931b585bb4449834637583

  amorail:
    usermail: "dev@coalla.ru"
    api_key: "07e0f3e6736762da760a2497b05197c4"
    api_endpoint: "https://cosmeticru.amocrm.ru/"

  shops_domains:
    cosmetic: cosmeticru.lvh.me
    barbershop: lvh.me
