loop do 
	puts "_____________________"
	puts "|        ^          |"
	puts "|        |          |"
	puts "|        |          |"
	puts "|        |          |"
	puts "|        ◻          |"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "_____________________"
	sleep 0.4
	puts "_____________________"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "|        ◻--------->|"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "_____________________"
	sleep 0.4
	puts "_____________________"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "|        ◻          |"
	puts "|        |          |"
	puts "|        |          |"
	puts "|        v          |"
	puts "_____________________"
	sleep 0.4
	puts "_____________________"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "|<-------◻          |"
	puts "|                   |"
	puts "|                   |"
	puts "|                   |"
	puts "_____________________"
	sleep 0.4
end
